use serde_json::Value;

use super::*;

/// Differential cases generated by node from jsdiff 8.0.4 and pi-durable
/// 1.0.4's `edit-diff.js`. `EUKHE_DURABLE_EDIT_DIFF_FIXTURE` names a larger
/// generated file to check instead.
fn fixture() -> Value {
    let path = std::env::var("EUKHE_DURABLE_EDIT_DIFF_FIXTURE").unwrap_or_else(|_| {
        concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/tests/fixtures/edit_diff_jsdiff.json"
        )
        .to_owned()
    });
    serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap()
}

fn str_of<'a>(value: &'a Value, key: &str) -> &'a str {
    value[key].as_str().unwrap()
}

fn usize_of(value: &Value, key: &str) -> usize {
    usize::try_from(value[key].as_u64().unwrap()).unwrap()
}

#[test]
fn matches_jsdiff_patches_and_diff_strings() {
    let fixture = fixture();
    let cases = fixture["diffs"].as_array().unwrap();
    assert!(!cases.is_empty());
    for (index, case) in cases.iter().enumerate() {
        let (old, new) = (str_of(case, "old"), str_of(case, "new"));
        let context = usize_of(case, "context");
        assert_eq!(
            generate_unified_patch("dir/f.txt", old, new, context),
            str_of(case, "patch"),
            "patch of case {index}: {old:?} -> {new:?}, context {context}"
        );
        let display = generate_diff_string(old, new, context);
        assert_eq!(
            display,
            DiffString {
                diff: str_of(case, "diff").to_owned(),
                first_changed_line: case["firstChangedLine"]
                    .as_u64()
                    .map(|line| usize::try_from(line).unwrap()),
            },
            "diff string of case {index}: {old:?} -> {new:?}, context {context}"
        );
    }
}

#[test]
fn matches_ts_edit_application() {
    let fixture = fixture();
    let cases = fixture["edits"].as_array().unwrap();
    assert!(!cases.is_empty());
    for (index, case) in cases.iter().enumerate() {
        let content = str_of(case, "content");
        let edits: Vec<Edit> = case["edits"]
            .as_array()
            .unwrap()
            .iter()
            .map(|edit| Edit {
                old_text: str_of(edit, "oldText").to_owned(),
                new_text: str_of(edit, "newText").to_owned(),
            })
            .collect();
        let actual = apply_edits_to_normalized_content(content, &edits, "f.txt");
        let expected = &case["result"];
        match (&actual, expected.get("ok")) {
            (Ok(result), Some(ok)) => assert_eq!(
                result,
                &AppliedEditsResult {
                    base_content: str_of(ok, "baseContent").to_owned(),
                    new_content: str_of(ok, "newContent").to_owned(),
                },
                "case {index}: {content:?} {edits:?}"
            ),
            (Err(error), None) => assert_eq!(
                error.to_string(),
                str_of(expected, "error"),
                "case {index}: {content:?} {edits:?}"
            ),
            _ => panic!("case {index}: {content:?} {edits:?}: {actual:?}, expected {expected}"),
        }
    }
}

#[test]
fn matches_ts_fuzzy_normalization() {
    let fixture = fixture();
    let cases = fixture["fuzzy"].as_array().unwrap();
    assert!(!cases.is_empty());
    for case in cases {
        let text = str_of(case, "text");
        assert_eq!(
            normalize_for_fuzzy_match(text),
            str_of(case, "normalized"),
            "{text:?}"
        );
    }
}

#[test]
fn trims_the_js_whitespace_set() {
    assert_eq!(
        normalize_for_fuzzy_match("a\u{FEFF}\nb\u{0085}\nc\u{2028}\n\u{180E}\u{1680}"),
        "a\nb\u{0085}\nc\n\u{180E}"
    );
}

#[test]
fn reports_utf16_offsets() {
    let found = fuzzy_find_text("🙂é x", "x");
    assert_eq!(
        found,
        FuzzyMatchResult {
            found: true,
            index: Some(4),
            match_length: 1,
            used_fuzzy_match: false,
            content_for_replacement: Cow::Borrowed("🙂é x"),
        }
    );
    let fuzzy = fuzzy_find_text("“🙂” —  \nx", "\"🙂\" -\nx");
    assert_eq!(
        fuzzy,
        FuzzyMatchResult {
            found: true,
            index: Some(0),
            match_length: 8,
            used_fuzzy_match: true,
            content_for_replacement: Cow::Owned("\"🙂\" -\nx".to_owned()),
        }
    );
    let missing = fuzzy_find_text("abc", "z");
    assert_eq!(
        missing,
        FuzzyMatchResult {
            found: false,
            index: None,
            match_length: 0,
            used_fuzzy_match: false,
            content_for_replacement: Cow::Borrowed("abc"),
        }
    );
}

#[test]
fn counts_an_empty_normalized_old_text_per_utf16_code_unit() {
    // `" "` normalizes to `""`, which JS `split` cuts into code units.
    assert_eq!(
        apply_edits_to_normalized_content(
            "🙂 a",
            &[Edit {
                old_text: " ".to_owned(),
                new_text: "_".to_owned(),
            }],
            "f.txt"
        ),
        Err(EditDiffError::Duplicate {
            path: "f.txt".to_owned(),
            edit_index: 0,
            total_edits: 1,
            occurrences: 3,
        })
    );
}

#[test]
fn detects_strips_and_restores_line_endings() {
    assert_eq!(detect_line_ending("a\r\nb\nc"), LineEnding::CrLf);
    assert_eq!(detect_line_ending("a\nb\r\nc"), LineEnding::Lf);
    assert_eq!(detect_line_ending("a\rb"), LineEnding::Lf);
    assert_eq!(normalize_to_lf("a\r\nb\rc\n"), "a\nb\nc\n");
    assert_eq!(restore_line_endings("a\nb", LineEnding::CrLf), "a\r\nb");
    assert_eq!(restore_line_endings("a\nb", LineEnding::Lf), "a\nb");
    assert_eq!(
        strip_bom("\u{FEFF}one"),
        BomSplit {
            bom: "\u{FEFF}",
            text: "one"
        }
    );
    assert_eq!(
        strip_bom("one"),
        BomSplit {
            bom: "",
            text: "one"
        }
    );
}

/// The helper half of the tools test "applies disjoint edits and returns both
/// diff formats".
#[test]
fn applies_disjoint_edits_and_returns_both_diff_formats() {
    let original = "alpha\nbeta\ngamma\ndelta\n";
    let applied = apply_edits_to_normalized_content(
        original,
        &[
            Edit {
                old_text: "alpha\n".to_owned(),
                new_text: "ALPHA\n".to_owned(),
            },
            Edit {
                old_text: "gamma\n".to_owned(),
                new_text: "GAMMA\n".to_owned(),
            },
        ],
        "edit.txt",
    )
    .unwrap();
    assert_eq!(
        applied,
        AppliedEditsResult {
            base_content: original.to_owned(),
            new_content: "ALPHA\nbeta\nGAMMA\ndelta\n".to_owned(),
        }
    );
    let diff = generate_diff_string(
        &applied.base_content,
        &applied.new_content,
        DEFAULT_CONTEXT_LINES,
    );
    assert_eq!(
        diff,
        DiffString {
            diff: "-1 alpha\n+1 ALPHA\n 2 beta\n-3 gamma\n+3 GAMMA\n 4 delta".to_owned(),
            first_changed_line: Some(1),
        }
    );
    assert_eq!(
        generate_unified_patch(
            "edit.txt",
            &applied.base_content,
            &applied.new_content,
            DEFAULT_CONTEXT_LINES
        ),
        "--- edit.txt\n+++ edit.txt\n@@ -1,4 +1,4 @@\n-alpha\n+ALPHA\n beta\n-gamma\n+GAMMA\n delta\n"
    );
}

#[test]
fn rejects_overlapping_missing_and_duplicate_edits() {
    let edit = |old_text: &str, new_text: &str| Edit {
        old_text: old_text.to_owned(),
        new_text: new_text.to_owned(),
    };
    assert_eq!(
        apply_edits_to_normalized_content(
            "one\ntwo\nthree\n",
            &[edit("one\ntwo\n", "ONE\nTWO\n"), edit("two\nthree\n", "TWO\nTHREE\n")],
            "edit.txt"
        )
        .unwrap_err()
        .to_string(),
        "edits[0] and edits[1] overlap in edit.txt. Merge them into one edit or target disjoint regions."
    );
    assert_eq!(
        apply_edits_to_normalized_content("foo foo foo", &[edit("bar", "baz")], "edit.txt")
            .unwrap_err()
            .to_string(),
        "Could not find the exact text in edit.txt. The old text must match exactly including all whitespace and newlines."
    );
    assert_eq!(
        apply_edits_to_normalized_content("foo foo foo", &[edit("foo", "bar")], "edit.txt")
            .unwrap_err()
            .to_string(),
        "Found 3 occurrences of the text in edit.txt. The text must be unique. Please provide more context to make it unique."
    );
    assert_eq!(
        apply_edits_to_normalized_content("foo", &[edit("foo", "foo")], "edit.txt")
            .unwrap_err()
            .to_string(),
        "No changes made to edit.txt. The replacement produced identical content. This might indicate an issue with special characters or the text not existing as expected."
    );
}
