//! Port of `test/cross-provider-handoff.test.ts`.
//!
//! Tests that contexts generated by one provider/model can be consumed by
//! another (tool call ID formats, thinking block transformation, message
//! formats). The TS `beforeAll` fixture generation runs once per test binary
//! through a shared `OnceCell`; both cases make real requests, so they are
//! `#[ignore]`d. TS `describe.skipIf(!hasAnyApiKey())` becomes a check that
//! fails with a clear message when no provider credential is set. TS
//! `resolveApiKey` (`test/oauth.ts`) reads `PI_TEST_<PROVIDER>_TOKEN`.

mod anthropic_support;
mod openai_responses_support;

use std::sync::{Arc, Mutex, PoisonError};
use std::time::{SystemTime, UNIX_EPOCH};

use anthropic_support::resolve_test_api_key;
use eukhe_pi_ai::compat::{complete_simple, get_env_api_key, get_model};
use eukhe_pi_ai::types::{OnPayload, ProviderHeaders, SimpleStreamOptions};
use eukhe_types::pi_ai::{
    AssistantContentBlock, AssistantMessage, Context, IndexMap, JsonValue, Message, Model,
    StopReason, ThinkingLevel,
};
use openai_responses_support::azure::has_azure_openai_credentials;
use serde_json::json;
use tokio::sync::OnceCell;

/// `Date.now()`.
fn now() -> u64 {
    let elapsed = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("clock after epoch");
    u64::try_from(elapsed.as_millis()).expect("epoch millis fit u64")
}

fn env_value(name: &str) -> Option<String> {
    std::env::var(name).ok().filter(|value| !value.is_empty())
}

/// TS `testTool`: `double_number` with a described `Type.Number`.
fn test_tool() -> JsonValue {
    json!({
        "name": "double_number",
        "description": "Doubles a number and returns the result",
        "parameters": {
            "type": "object",
            "properties": {
                "value": { "description": "A number to double", "type": "number" },
            },
            "required": ["value"],
        },
    })
}

/// TS `ProviderModelPair`.
struct ProviderModelPair {
    provider: &'static str,
    model: &'static str,
    label: &'static str,
    api_override: Option<&'static str>,
    upstream_api_key_env: Option<&'static str>,
}

const fn pair(
    provider: &'static str,
    model: &'static str,
    label: &'static str,
) -> ProviderModelPair {
    ProviderModelPair {
        provider,
        model,
        label,
        api_override: None,
        upstream_api_key_env: None,
    }
}

const fn with_api_override(mut pair: ProviderModelPair, api: &'static str) -> ProviderModelPair {
    pair.api_override = Some(api);
    pair
}

const fn with_upstream_api_key_env(
    mut pair: ProviderModelPair,
    env: &'static str,
) -> ProviderModelPair {
    pair.upstream_api_key_env = Some(env);
    pair
}

const PROVIDER_MODEL_PAIRS: &[ProviderModelPair] = &[
    // Anthropic
    pair(
        "anthropic",
        "claude-sonnet-4-5",
        "anthropic-claude-sonnet-4-5",
    ),
    // Google
    pair(
        "google",
        "gemini-3-flash-preview",
        "google-gemini-3-flash-preview",
    ),
    // OpenAI
    with_api_override(
        pair("openai", "gpt-4o-mini", "openai-completions-gpt-4o-mini"),
        "openai-completions",
    ),
    pair("openai", "gpt-5-mini", "openai-responses-gpt-5-mini"),
    pair("azure", "gpt-4o-mini", "azure-gpt-4o-mini"),
    // OpenAI Codex
    pair("openai-codex", "gpt-5.5", "openai-codex-gpt-5.5"),
    // GitHub Copilot
    pair(
        "github-copilot",
        "claude-sonnet-4.5",
        "copilot-claude-sonnet-4.5",
    ),
    pair("github-copilot", "gpt-5.1-codex", "copilot-gpt-5.1-codex"),
    pair(
        "github-copilot",
        "gemini-3-flash-preview",
        "copilot-gemini-3-flash-preview",
    ),
    pair(
        "github-copilot",
        "grok-code-fast-1",
        "copilot-grok-code-fast-1",
    ),
    // Amazon Bedrock
    pair(
        "amazon-bedrock",
        "global.anthropic.claude-sonnet-4-5-20250929-v1:0",
        "bedrock-claude-sonnet-4-5",
    ),
    // xAI
    pair("xai", "grok-4.3", "xai-grok-4.3"),
    // Cerebras
    pair("cerebras", "zai-glm-4.7", "cerebras-zai-glm-4.7"),
    // Cloudflare Workers AI
    pair(
        "cloudflare-workers-ai",
        "@cf/moonshotai/kimi-k2.6",
        "cloudflare-kimi-k2.6",
    ),
    // Cloudflare AI Gateway
    pair(
        "cloudflare-ai-gateway",
        "workers-ai/@cf/moonshotai/kimi-k2.6",
        "cloudflare-gateway-kimi-k2.6",
    ),
    with_upstream_api_key_env(
        pair(
            "cloudflare-ai-gateway",
            "claude-sonnet-4-5",
            "cloudflare-gateway-claude-sonnet-4-5",
        ),
        "ANTHROPIC_API_KEY",
    ),
    with_upstream_api_key_env(
        pair(
            "cloudflare-ai-gateway",
            "gpt-5.1",
            "cloudflare-gateway-gpt-5.1",
        ),
        "OPENAI_API_KEY",
    ),
    // Groq
    pair("groq", "openai/gpt-oss-120b", "groq-gpt-oss-120b"),
    // Hugging Face
    pair(
        "huggingface",
        "moonshotai/Kimi-K2.5",
        "huggingface-kimi-k2.5",
    ),
    // Together AI
    pair("together", "moonshotai/Kimi-K3", "together-kimi-k3"),
    // Baseten
    pair("baseten", "zai-org/GLM-5.2", "baseten-glm-5.2"),
    // Kimi For Coding
    pair("kimi-coding", "kimi-for-coding", "kimi-for-coding"),
    // Meta
    pair("meta", "muse-spark-1.3", "meta-muse-spark-1.3"),
    // Mistral
    pair(
        "mistral",
        "devstral-medium-latest",
        "mistral-devstral-medium",
    ),
    // MiniMax
    pair("minimax", "MiniMax-M2.7", "minimax-m2.7"),
    pair("minimax-cn", "MiniMax-M2.7", "minimax-m2.7"),
    // OpenCode Zen
    pair("opencode", "big-pickle", "zen-big-pickle"),
    pair("opencode", "claude-sonnet-4-5", "zen-claude-sonnet-4-5"),
    pair("opencode", "gemini-3-flash", "zen-gemini-3-flash"),
    pair("opencode", "glm-4.7-free", "zen-glm-4.7-free"),
    pair("opencode", "gpt-5.2-codex", "zen-gpt-5.2-codex"),
    pair("opencode", "minimax-m2.1-free", "zen-minimax-m2.1-free"),
    // OpenCode Go
    pair("opencode-go", "kimi-k2.5", "go-kimi-k2.5"),
    pair("opencode-go", "minimax-m2.5", "go-minimax-m2.5"),
    // Xiaomi MiMo
    pair("xiaomi", "mimo-v2.5-pro", "xiaomi-mimo-v2.5-pro"),
    pair(
        "xiaomi-token-plan-cn",
        "mimo-v2.5-pro",
        "xiaomi-token-plan-cn-mimo-v2.5-pro",
    ),
    pair(
        "xiaomi-token-plan-ams",
        "mimo-v2.5-pro",
        "xiaomi-token-plan-ams-mimo-v2.5-pro",
    ),
    pair(
        "xiaomi-token-plan-sgp",
        "mimo-v2.5-pro",
        "xiaomi-token-plan-sgp-mimo-v2.5-pro",
    ),
    // Qwen Token Plan
    pair(
        "qwen-token-plan",
        "qwen3.7-max",
        "qwen-token-plan-qwen3.7-max",
    ),
    pair(
        "qwen-token-plan-cn",
        "qwen3.7-max",
        "qwen-token-plan-cn-qwen3.7-max",
    ),
    pair(
        "qwen-token-plan-individual",
        "qwen3.8-max",
        "qwen-token-plan-individual-qwen3.8-max",
    ),
    pair(
        "qwen-token-plan-individual",
        "deepseek-v4-flash-0731",
        "qwen-token-plan-individual-deepseek-v4-flash-0731",
    ),
    pair(
        "qwen-token-plan-individual",
        "glm-5.2",
        "qwen-token-plan-individual-glm-5.2",
    ),
];

/// TS `CachedContext`, reduced to what the handoff case reads back (the TS
/// record's `label`/`provider`/`model`/`api`/`generatedAt` are never read).
#[derive(Debug)]
struct CachedContext {
    messages: Vec<Message>,
}

/// The TS `beforeAll` state: `contexts` keeps JS object key order (a
/// repeated label keeps its first position and takes the later value).
struct Fixtures {
    contexts: IndexMap<String, CachedContext>,
    available_pairs: Vec<&'static ProviderModelPair>,
}

/// Get API key for provider - checks OAuth storage first, then env vars.
fn get_api_key(provider: &str) -> Option<String> {
    resolve_test_api_key(provider).or_else(|| get_env_api_key(provider, None))
}

/// Synchronous check for API key availability (env vars only, for skipIf).
fn has_api_key(pair: &ProviderModelPair) -> bool {
    match pair.provider {
        "azure" => has_azure_openai_credentials(),
        "cloudflare-workers-ai" => {
            env_value("CLOUDFLARE_API_KEY").is_some()
                && env_value("CLOUDFLARE_ACCOUNT_ID").is_some()
        }
        "cloudflare-ai-gateway" => {
            let has_gateway = env_value("CLOUDFLARE_API_KEY").is_some()
                && env_value("CLOUDFLARE_ACCOUNT_ID").is_some()
                && env_value("CLOUDFLARE_GATEWAY_ID").is_some();
            has_gateway
                && pair
                    .upstream_api_key_env
                    .is_none_or(|name| env_value(name).is_some())
        }
        provider => get_env_api_key(provider, None).is_some(),
    }
}

fn get_headers(pair: &ProviderModelPair) -> Option<ProviderHeaders> {
    let upstream_api_key = env_value(pair.upstream_api_key_env?)?;
    Some(ProviderHeaders::from([(
        "Authorization".to_owned(),
        Some(format!("Bearer {upstream_api_key}")),
    )]))
}

/// Check if any provider has API keys available (for skipIf at describe level).
fn has_any_api_key() -> bool {
    PROVIDER_MODEL_PAIRS.iter().any(has_api_key)
}

fn require_any_api_key() {
    assert!(
        has_any_api_key(),
        "no provider credentials set (provider API key env vars, AZURE_OPENAI_*, CLOUDFLARE_*, or PI_TEST_<PROVIDER>_TOKEN)"
    );
}

fn dump_failure_payload(
    label: &str,
    error: &str,
    payload: Option<JsonValue>,
    messages: &[Message],
) {
    let filename = format!("/tmp/pi-handoff-{label}-{}.json", now());
    // `JSON.stringify` drops an `undefined` payload.
    let mut body = serde_json::Map::new();
    body.insert("label".into(), json!(label));
    body.insert("error".into(), json!(error));
    if let Some(payload) = payload {
        body.insert("payload".into(), payload);
    }
    body.insert(
        "messages".into(),
        serde_json::to_value(messages).expect("messages json"),
    );
    let text = serde_json::to_string_pretty(&JsonValue::Object(body)).expect("payload json");
    std::fs::write(&filename, text).unwrap_or_else(|error| panic!("write {filename}: {error}"));
    println!("Wrote failure payload to {filename}");
}

type LastPayload = Arc<Mutex<Option<JsonValue>>>;

/// `onPayload: (payload) => { lastPayload = payload; }`.
fn recording_on_payload(last: &LastPayload) -> OnPayload<Model> {
    let sink = Arc::clone(last);
    Arc::new(move |payload, _model| {
        *sink.lock().unwrap_or_else(PoisonError::into_inner) = Some(payload);
        Box::pin(async { Ok(None) })
    })
}

fn last_payload(last: &LastPayload) -> Option<JsonValue> {
    last.lock().unwrap_or_else(PoisonError::into_inner).clone()
}

fn resolve_model(pair: &ProviderModelPair) -> Option<Model> {
    let mut model = get_model(pair.provider, pair.model)?;
    if let Some(api) = pair.api_override {
        model.api = api.into();
    }
    Some(model)
}

fn simple_options(
    model: &Model,
    pair: &ProviderModelPair,
    api_key: &str,
    last: &LastPayload,
) -> SimpleStreamOptions {
    let mut options = SimpleStreamOptions::default();
    options.stream.request.api_key = Some(api_key.to_owned());
    options.reasoning = model.reasoning.then_some(ThinkingLevel::High);
    options.stream.request.headers = get_headers(pair);
    options.stream.request.on_payload = Some(recording_on_payload(last));
    options
}

fn context(system_prompt: &str, messages: &[Message]) -> Context {
    serde_json::from_value(json!({
        "systemPrompt": system_prompt,
        "messages": messages,
        "tools": [test_tool()],
    }))
    .expect("context")
}

/// The shared inputs of one fixture `completeSimple` call.
#[derive(Clone, Copy)]
struct FixtureRequest<'a> {
    model: &'a Model,
    pair: &'a ProviderModelPair,
    api_key: &'a str,
    last: &'a LastPayload,
}

/// Which fixture request failed (TS log text and dump label suffix).
#[derive(Clone, Copy)]
enum FixtureStage {
    Initial,
    Final,
}

impl FixtureStage {
    const fn log_name(self) -> &'static str {
        match self {
            Self::Initial => "Initial",
            Self::Final => "Final",
        }
    }

    const fn label_suffix(self) -> &'static str {
        match self {
            Self::Initial => "initial",
            Self::Final => "final",
        }
    }
}

/// One fixture `completeSimple`; logs and dumps the payload on failure.
async fn fixture_request(
    request: FixtureRequest<'_>,
    stage: FixtureStage,
    system_prompt: &str,
    messages: &[Message],
) -> Option<AssistantMessage> {
    let label = format!("{}-{}", request.pair.label, stage.label_suffix());
    let response = match complete_simple(
        request.model,
        context(system_prompt, messages),
        simple_options(request.model, request.pair, request.api_key, request.last),
    )
    .await
    {
        Ok(response) => response,
        Err(error) => {
            let msg = error.to_string();
            println!("  {} request failed: {msg}", stage.log_name());
            dump_failure_payload(&label, &msg, last_payload(request.last), messages);
            return None;
        }
    };

    if response.stop_reason == StopReason::Error {
        println!(
            "  {} request error: {}",
            stage.log_name(),
            response.error_message.as_deref().unwrap_or("undefined")
        );
        dump_failure_payload(
            &label,
            response
                .error_message
                .as_deref()
                .filter(|message| !message.is_empty())
                .unwrap_or("Unknown error"),
            last_payload(request.last),
            messages,
        );
        return None;
    }
    Some(response)
}

/// Generate a context from a provider/model pair. Makes a real API call to
/// get authentic tool call IDs and thinking blocks.
async fn generate_context(pair: &ProviderModelPair, api_key: &str) -> Option<Vec<Message>> {
    let Some(model) = resolve_model(pair) else {
        println!("  Model not found: {}/{}", pair.provider, pair.model);
        return None;
    };

    let user_message: Message = serde_json::from_value(json!({
        "role": "user",
        "content": "Please double the number 21 using the double_number tool.",
        "timestamp": now(),
    }))
    .expect("user message");

    let last: LastPayload = Arc::default();
    let request = FixtureRequest {
        model: &model,
        pair,
        api_key,
        last: &last,
    };
    let initial_messages = vec![user_message.clone()];
    let assistant_response = fixture_request(
        request,
        FixtureStage::Initial,
        "You are a helpful assistant. Use the provided tool to complete the task.",
        &initial_messages,
    )
    .await?;

    let tool_call = assistant_response
        .content
        .iter()
        .find_map(|block| match block {
            AssistantContentBlock::ToolCall(tool_call) => Some(tool_call.clone()),
            _ => None,
        });
    let Some(tool_call) = tool_call else {
        println!(
            "  No tool call in response (stopReason: {:?})",
            assistant_response.stop_reason
        );
        return Some(vec![user_message, Message::Assistant(assistant_response)]);
    };

    println!("  Tool call ID: {}", tool_call.id);

    let tool_result: Message = serde_json::from_value(json!({
        "role": "toolResult",
        "toolCallId": tool_call.id,
        "toolName": tool_call.name,
        "content": [{ "type": "text", "text": "42" }],
        "isError": false,
        "timestamp": now(),
    }))
    .expect("tool result");

    let messages_for_final = vec![
        user_message,
        Message::Assistant(assistant_response),
        tool_result,
    ];
    let final_response = fixture_request(
        request,
        FixtureStage::Final,
        "You are a helpful assistant.",
        &messages_for_final,
    )
    .await?;

    let mut messages = messages_for_final;
    messages.push(Message::Assistant(final_response));
    Some(messages)
}

/// TS `beforeAll`.
async fn generate_fixtures() -> Fixtures {
    let mut fixtures = Fixtures {
        contexts: IndexMap::new(),
        available_pairs: Vec::new(),
    };

    println!("\n=== Generating Fixtures ===\n");

    for pair in PROVIDER_MODEL_PAIRS {
        let Some(api_key) = get_api_key(pair.provider).filter(|_| has_api_key(pair)) else {
            println!("[{}] Skipping - no auth for {}", pair.label, pair.provider);
            continue;
        };

        println!("[{}] Generating fixture...", pair.label);
        let result = generate_context(pair, &api_key).await;

        let Some(messages) = result.filter(|messages| messages.len() >= 4) else {
            println!("[{}] Failed to generate fixture, skipping", pair.label);
            continue;
        };

        let count = messages.len();
        fixtures
            .contexts
            .insert(pair.label.to_owned(), CachedContext { messages });
        fixtures.available_pairs.push(pair);
        println!("[{}] Generated {count} messages", pair.label);
    }

    println!(
        "\n=== {}/{} contexts available ===\n",
        fixtures.available_pairs.len(),
        PROVIDER_MODEL_PAIRS.len()
    );
    fixtures
}

static FIXTURES: OnceCell<Fixtures> = OnceCell::const_new();

async fn fixtures() -> &'static Fixtures {
    FIXTURES.get_or_init(generate_fixtures).await
}

/// JS `text.slice(0, 100)` (UTF-16 code units).
fn preview(text: &str) -> String {
    let units: Vec<u16> = text.encode_utf16().take(100).collect();
    String::from_utf16_lossy(&units).replace('\n', " ")
}

struct HandoffResult {
    target: &'static str,
    success: bool,
    error: Option<String>,
}

/// The handoff `completeSimple` against one target.
async fn handoff_request(
    model: &Model,
    target_pair: &'static ProviderModelPair,
    api_key: &str,
    all_messages: &[Message],
) -> HandoffResult {
    let last: LastPayload = Arc::default();
    match complete_simple(
        model,
        context("You are a helpful assistant.", all_messages),
        simple_options(model, target_pair, api_key, &last),
    )
    .await
    {
        Ok(response) if response.stop_reason == StopReason::Error => {
            println!(
                "[Target: {}] FAILED: {}",
                target_pair.label,
                response.error_message.as_deref().unwrap_or("undefined")
            );
            dump_failure_payload(
                target_pair.label,
                response
                    .error_message
                    .as_deref()
                    .filter(|message| !message.is_empty())
                    .unwrap_or("Unknown error"),
                last_payload(&last),
                all_messages,
            );
            HandoffResult {
                target: target_pair.label,
                success: false,
                error: response.error_message,
            }
        }
        Ok(response) => {
            let text = response
                .content
                .iter()
                .filter_map(|block| match block {
                    AssistantContentBlock::Text(text) => Some(text.text.as_str()),
                    _ => None,
                })
                .collect::<Vec<_>>()
                .join(" ");
            println!(
                "[Target: {}] SUCCESS: {}...",
                target_pair.label,
                preview(&text)
            );
            HandoffResult {
                target: target_pair.label,
                success: true,
                error: None,
            }
        }
        Err(error) => {
            let msg = error.to_string();
            println!("[Target: {}] EXCEPTION: {msg}", target_pair.label);
            dump_failure_payload(target_pair.label, &msg, last_payload(&last), all_messages);
            HandoffResult {
                target: target_pair.label,
                success: false,
                error: Some(msg),
            }
        }
    }
}

#[tokio::test]
#[ignore = "needs provider credentials (provider API key env vars, AZURE_OPENAI_*, CLOUDFLARE_*, or PI_TEST_<PROVIDER>_TOKEN); run with --ignored"]
async fn should_have_at_least_2_fixtures_to_test_handoffs() {
    require_any_api_key();
    assert!(fixtures().await.contexts.len() >= 2);
}

#[tokio::test]
#[ignore = "needs provider credentials (provider API key env vars, AZURE_OPENAI_*, CLOUDFLARE_*, or PI_TEST_<PROVIDER>_TOKEN); run with --ignored"]
async fn should_handle_cross_provider_handoffs_for_each_target() {
    require_any_api_key();
    let fixtures = fixtures().await;

    if fixtures.contexts.len() < 2 {
        println!("Not enough fixtures for handoff test, skipping");
        return;
    }

    println!("\n=== Testing Cross-Provider Handoffs ===\n");

    let mut results: Vec<HandoffResult> = Vec::new();

    for target_pair in &fixtures.available_pairs {
        let Some(api_key) = get_api_key(target_pair.provider).filter(|_| has_api_key(target_pair))
        else {
            println!("[Target: {}] Skipping - no auth", target_pair.label);
            continue;
        };

        // Collect messages from ALL OTHER contexts
        let other_messages: Vec<Message> = fixtures
            .contexts
            .iter()
            .filter(|(label, _)| label.as_str() != target_pair.label)
            .flat_map(|(_, ctx)| ctx.messages.iter().cloned())
            .collect();

        if other_messages.is_empty() {
            println!(
                "[Target: {}] Skipping - no other contexts",
                target_pair.label
            );
            continue;
        }

        let mut all_messages = other_messages;
        let other_count = all_messages.len();
        all_messages.push(
            serde_json::from_value(json!({
                "role": "user",
                "content": "Great, thanks for all that help! Now just say 'Hello, handoff successful!' to confirm you received everything.",
                "timestamp": now(),
            }))
            .expect("user message"),
        );

        let Some(model) = resolve_model(target_pair) else {
            println!("[Target: {}] Model not found", target_pair.label);
            continue;
        };

        println!(
            "[Target: {}] Testing with {other_count} messages from other providers...",
            target_pair.label
        );

        results.push(handoff_request(&model, target_pair, &api_key, &all_messages).await);
    }

    println!("\n=== Results Summary ===\n");
    let successes = results.iter().filter(|result| result.success).count();
    let failures: Vec<&HandoffResult> = results.iter().filter(|result| !result.success).collect();

    println!("Passed: {successes}/{}", results.len());
    if !failures.is_empty() {
        println!("\nFailures:");
        for failure in &failures {
            println!(
                "  - {}: {}",
                failure.target,
                failure.error.as_deref().unwrap_or("undefined")
            );
        }
    }

    assert_eq!(failures.len(), 0);
}
