//! Cross-implementation check of the Harness against the TS package (no TS
//! test file): a process dies while a tool call runs, and the other
//! implementation picks the conversation up from the JSONL storage it left.
//!
//! Both sides run the same scenario: a Harness over JSONL storage with the
//! clock fixed at [`NOW`], a faux provider (`api: "faux"`, one chunk per
//! block) answering "Probe the disk." with the `probe` tool call `call-1`;
//! `probe` (replay `unsafe`, the default) reports output, a diagnostic, and
//! details, then the process exits once the details are durable. The resume
//! answers with a final text, waits for idle, and dumps the state.
//! The TS side ran the same steps as [`open`], [`crash`], [`resume`], and
//! [`dump_storage`] here, spelled with the TS API (`openNodeJsonlStorage`,
//! `fauxProvider`, `defineTool`, `Harness.open(storage, { models, registry,
//! now })`).
//!
//! `fixtures/harness_cross` (written by `@earendil-works/pi-durable` 1.1,
//! `main` at `42a3497d0`, and this crate):
//! - `ts-crash/`: the JSONL storage the TS process left (`process.exit(0)` in
//!   `execute`).
//! - `ts-crash-resumed.json` / `ts-crash-resumed/`: the final state and the
//!   JSONL files after TS resumed a copy of `ts-crash/`.
//! - `rust-crash/`: the JSONL storage a child process of this test left
//!   (`std::process::exit(0)` in `execute`), regenerated by the ignored
//!   `regenerate_rust_crash_fixture`.
//! - `rust-crash-resumed.json` / `rust-crash-resumed/`: the final state and
//!   the JSONL files after TS resumed a copy of `rust-crash/`.
//!
//! The final state is `{ toolRuns, context, storage }`: how often `probe` ran
//! during the resume (TS does not rerun an `unsafe` call: 0), the root's
//! `context()` view (`entries`, `contributions`, `messages`), and every record
//! the Storage API returns after close: conversations, each conversation's
//! entries oldest first, tasks, submissions, and every document alive at
//! `current` in the session, conversation, and task scopes, materialized.
//! States compare as `JSON.stringify` text (key order included); JSONL files
//! compare byte for byte. The only normalization is the `pi.provider`
//! document's `sessionId`, a random `UUIDv7` minted at conversation creation,
//! when a fresh crash run is compared with a fixture.
//!
//! The faux messages carry no `responseId`: TS `fauxAssistantMessage()`
//! writes it after `stopReason`, while `AssistantMessage` serializes in the
//! TS interface order (after `model`), so the stored message's key order
//! would differ for a reason outside the Harness.

use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::Arc;

use eukhe_chord::context::{Context, BACKGROUND_CONTEXT};
use eukhe_chord::json::{from_json, to_json, JsonObject, JsonValue};
use eukhe_durable::harness::define::{define_extension, define_tool};
use eukhe_durable::harness::registry::create_registry;
use eukhe_durable::harness::types::{
    AgentChange, ContextView, Extension, FieldChange, HarnessOptions, InputSubmissionDraft,
    ModelRef, ToolDiagnostic, ToolDiagnosticSeverity, ToolExecutionResult, ToolOutputChunk,
    ToolRegistration,
};
use eukhe_durable::harness::{Conversation, Harness, RootOptions};
use eukhe_durable::storage::jsonl::{open_native_jsonl_storage, JsonlStorageOptions};
use eukhe_durable::types::{
    ConversationQuery, Cursor, DocumentPoint, DocumentQuery, EntryQuery, Storage, SubmissionQuery,
    TaskQuery,
};
use eukhe_pi_ai::models::{create_models, CreateModelsOptions};
use eukhe_pi_ai::providers::faux::{
    faux_assistant_message, faux_provider, faux_text, faux_tool_call, FauxAssistantMessageOptions,
    FauxProviderHandle, FauxTokenSize, RegisterFauxProviderOptions,
};
use eukhe_pi_ai::typebox::Type;
use eukhe_types::pi_ai::{
    AssistantMessage, JsonObject as PiJsonObject, StopReason, TextContent, UserContentBlock,
};
use serde::Serialize;

/// The fixed Harness clock and faux message timestamp.
const NOW: u64 = 1_000_000;

/// Set in the child process this test spawns: crash into that directory.
const CRASH_DIR_ENV: &str = "EUKHE_DURABLE_HARNESS_CROSS_CRASH_DIR";

fn cx() -> &'static Context {
    &BACKGROUND_CONTEXT
}

fn fixtures() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/harness_cross")
}

/// What `probe` does once its details are durable.
#[derive(Clone, Copy)]
enum AfterDetails {
    /// Die like a crashed process (TS `process.exit(0)`).
    Exit,
    /// Finish normally.
    Finish,
}

fn probe_tool(after: AfterDetails, runs: Arc<AtomicUsize>) -> Arc<ToolRegistration> {
    define_tool(ToolRegistration::new(
        "probe",
        "Probe the durable tool slot",
        Type::object([("target", Type::string())]),
        move |args, api, call_cx| {
            runs.fetch_add(1, Ordering::SeqCst);
            async move {
                let target = args["target"].as_str().unwrap_or_default().to_owned();
                api.output(ToolOutputChunk::Text(&format!("probing {target}\n")), None)?;
                api.diagnostic(ToolDiagnostic {
                    severity: ToolDiagnosticSeverity::Info,
                    code: Some("probe".to_owned()),
                    message: "probe started".to_owned(),
                })?;
                let details = serde_json::json!({ "step": 1, "target": target });
                api.details(JsonValue::from(details), &call_cx).await?;
                match after {
                    AfterDetails::Exit => std::process::exit(0),
                    AfterDetails::Finish => Ok(ToolExecutionResult {
                        output: Some(vec![UserContentBlock::Text(TextContent::new(
                            "probe finished",
                        ))]),
                        ..ToolExecutionResult::default()
                    }),
                }
            }
        },
    ))
}

fn call_probe() -> AssistantMessage {
    let mut arguments = PiJsonObject::new();
    arguments.insert("target".to_owned(), "disk".into());
    faux_assistant_message(
        vec![faux_tool_call(
            "probe",
            arguments,
            Some("call-1".to_owned()),
        )],
        FauxAssistantMessageOptions {
            stop_reason: Some(StopReason::ToolUse),
            timestamp: Some(NOW),
            ..FauxAssistantMessageOptions::default()
        },
    )
}

fn answer() -> AssistantMessage {
    faux_assistant_message(
        vec![faux_text("The probe was interrupted.")],
        FauxAssistantMessageOptions {
            timestamp: Some(NOW),
            ..FauxAssistantMessageOptions::default()
        },
    )
}

fn path_str(path: &Path) -> &str {
    path.to_str().unwrap()
}

async fn open_storage(directory: &Path) -> Arc<dyn Storage> {
    Arc::new(
        open_native_jsonl_storage(path_str(directory), cx(), JsonlStorageOptions::default())
            .await
            .unwrap(),
    )
}

struct Opened {
    faux: FauxProviderHandle,
    harness: Harness,
    root: Conversation,
    runs: Arc<AtomicUsize>,
}

/// Open the Harness over the JSONL directory, with `probe` installed and the
/// root on the faux model.
async fn open(directory: &Path, after: AfterDetails) -> Opened {
    let faux = faux_provider(RegisterFauxProviderOptions {
        api: Some("faux".to_owned()),
        token_size: Some(FauxTokenSize {
            min: Some(1000),
            max: Some(1000),
        }),
        ..RegisterFauxProviderOptions::default()
    });
    let models = create_models(CreateModelsOptions::default());
    models.set_provider(faux.provider.clone());
    let runs = Arc::new(AtomicUsize::new(0));
    let registry = create_registry();
    registry
        .install(define_extension(Extension {
            tools: vec![probe_tool(after, Arc::clone(&runs))],
            ..Extension::named("probe")
        }))
        .unwrap();
    let mut options = HarnessOptions::new(models, Arc::new(registry));
    #[expect(
        clippy::cast_precision_loss,
        reason = "NOW is a small whole number of milliseconds"
    )]
    let now = NOW as f64;
    options.now = Some(Arc::new(move || now));
    let harness = Harness::open(open_storage(directory).await, options, cx())
        .await
        .unwrap();
    let root = harness
        .root(
            RootOptions {
                agent: Some(AgentChange {
                    model: FieldChange::Set(ModelRef {
                        provider: "faux".to_owned(),
                        model_id: "faux-1".to_owned(),
                    }),
                    ..AgentChange::default()
                }),
                ..RootOptions::default()
            },
            cx(),
        )
        .await
        .unwrap();
    Opened {
        faux,
        harness,
        root,
        runs,
    }
}

/// The child process: submit the input and die inside `probe`.
async fn crash(directory: &Path) -> ! {
    let opened = open(directory, AfterDetails::Exit).await;
    opened.faux.set_responses(vec![call_probe().into()]);
    let submission = opened
        .root
        .submit(InputSubmissionDraft::new("Probe the disk."), cx())
        .await
        .unwrap();
    submission.wait(cx()).await.unwrap();
    panic!("the tool never crashed");
}

/// Run [`crash`] in a child process of this test binary.
fn crash_in_child(test_name: &str, directory: &Path) {
    let status = Command::new(std::env::current_exe().unwrap())
        .args([
            "--exact",
            test_name,
            "--include-ignored",
            "--nocapture",
            "--test-threads=1",
        ])
        .env(CRASH_DIR_ENV, directory)
        .status()
        .unwrap();
    assert!(status.success(), "the crash child failed: {status}");
}

fn json<T: Serialize>(value: &T) -> JsonValue {
    to_json(value).unwrap()
}

fn object<const N: usize>(fields: [(&str, JsonValue); N]) -> JsonValue {
    let mut object = JsonObject::new();
    for (key, value) in fields {
        object.insert(key, value);
    }
    JsonValue::from(object)
}

fn query<T: serde::de::DeserializeOwned>(value: serde_json::Value) -> T {
    from_json(&JsonValue::from(value)).unwrap()
}

/// Every page of one Storage scan.
macro_rules! scan_all {
    ($storage:expr, $method:ident, $query:expr) => {{
        let query = $query;
        let mut items = Vec::new();
        let mut cursor: Option<Cursor> = None;
        loop {
            let page = $storage
                .$method(&query, 100, cursor.as_ref(), cx())
                .await
                .unwrap();
            items.extend(page.items);
            match page.next {
                Some(next) => cursor = Some(next),
                None => break items,
            }
        }
    }};
}

/// TS `dumpStorage`: everything a reader observes through the Storage API.
async fn dump_storage(storage: &dyn Storage) -> JsonValue {
    let conversations = scan_all!(
        storage,
        scan_conversations,
        query::<ConversationQuery>(serde_json::json!({}))
    );
    let mut entries = Vec::new();
    for conversation in &conversations {
        let mut items = scan_all!(
            storage,
            scan_entries,
            query::<EntryQuery>(serde_json::json!({ "conversationId": conversation.id }))
        );
        items.reverse();
        entries.push(object([
            ("conversationId", json(&conversation.id)),
            ("entries", json(&items)),
        ]));
    }
    let tasks = scan_all!(
        storage,
        scan_tasks,
        query::<TaskQuery>(serde_json::json!({}))
    );
    let submissions = scan_all!(
        storage,
        scan_submissions,
        query::<SubmissionQuery>(serde_json::json!({}))
    );
    let mut scopes = vec![serde_json::json!({ "kind": "session" })];
    scopes.extend(conversations.iter().map(|conversation| {
        serde_json::json!({ "kind": "conversation", "conversationId": conversation.id })
    }));
    scopes.extend(
        tasks
            .iter()
            .map(|task| serde_json::json!({ "kind": "task", "taskId": task.id })),
    );
    let mut documents = Vec::new();
    for scope in scopes {
        let records = scan_all!(
            storage,
            scan_documents,
            query::<DocumentQuery>(serde_json::json!({ "scope": scope, "at": "current" }))
        );
        for record in records {
            let document = storage
                .document(record.id, DocumentPoint::Current, cx())
                .await
                .unwrap();
            documents.push(json(&document));
        }
    }
    object([
        ("conversations", json(&conversations)),
        ("entries", JsonValue::Array(Arc::new(entries))),
        ("tasks", json(&tasks)),
        ("submissions", json(&submissions)),
        ("documents", JsonValue::Array(Arc::new(documents))),
    ])
}

/// TS `ContextView` as `JSON.stringify` writes it (`head` omitted when
/// absent).
fn context_json(view: &ContextView) -> JsonValue {
    let mut object = JsonObject::new();
    if let Some(head) = &view.head {
        object.insert("head", json(head));
    }
    object.insert("entries", json(&view.entries));
    object.insert("contributions", json(&view.contributions));
    object.insert("messages", json(&view.messages));
    JsonValue::from(object)
}

/// Resume the crashed storage in `directory` (TS `resume.ts`) and return the
/// final state.
async fn resume(directory: &Path) -> JsonValue {
    let opened = open(directory, AfterDetails::Finish).await;
    opened.faux.set_responses(vec![answer().into()]);
    opened.harness.wait_for_idle(cx()).await.unwrap();
    let view = opened
        .root
        .context(
            cx(),
            eukhe_durable::harness::types::ContextOptions::default(),
        )
        .await
        .unwrap();
    opened.harness.close(cx()).await.unwrap();
    let storage = open_storage(directory).await;
    let dump = dump_storage(&*storage).await;
    storage.close(cx()).await.unwrap();
    object([
        ("toolRuns", json(&opened.runs.load(Ordering::SeqCst))),
        ("context", context_json(&view)),
        ("storage", dump),
    ])
}

fn copy_dir(source: &Path, target: &Path) {
    std::fs::create_dir_all(target).unwrap();
    for entry in std::fs::read_dir(source).unwrap() {
        let entry = entry.unwrap();
        std::fs::copy(entry.path(), target.join(entry.file_name())).unwrap();
    }
}

/// The directory's files, sorted by name, as text.
fn files(directory: &Path) -> Vec<(String, String)> {
    let mut files: Vec<(String, String)> = std::fs::read_dir(directory)
        .unwrap()
        .map(|entry| {
            let entry = entry.unwrap();
            (
                entry.file_name().into_string().unwrap(),
                std::fs::read_to_string(entry.path()).unwrap(),
            )
        })
        .collect();
    files.sort();
    files
}

#[track_caller]
fn assert_same_files(actual: &[(String, String)], expected: &[(String, String)]) {
    let names = |files: &[(String, String)]| {
        files
            .iter()
            .map(|(name, _)| name.clone())
            .collect::<Vec<_>>()
    };
    assert_eq!(names(actual), names(expected));
    for ((name, actual), (_, expected)) in actual.iter().zip(expected) {
        assert_eq!(actual, expected, "{name}");
    }
}

/// Replace every `"sessionId":"<uuid>"` value: the `pi.provider` document's
/// random `UUIDv7`, the one value two crash runs legitimately disagree on.
fn without_session_ids(files: Vec<(String, String)>) -> Vec<(String, String)> {
    const KEY: &str = "\"sessionId\":\"";
    files
        .into_iter()
        .map(|(name, text)| {
            let mut normalized = String::with_capacity(text.len());
            let mut rest = text.as_str();
            while let Some(start) = rest.find(KEY) {
                let value = start + KEY.len();
                let end = value + rest[value..].find('"').unwrap();
                normalized.push_str(&rest[..value]);
                normalized.push_str("<session>");
                rest = &rest[end..];
            }
            normalized.push_str(rest);
            (name, normalized)
        })
        .collect()
}

/// Compare section by section first, for readable failures, then whole.
#[track_caller]
fn assert_same_state(actual: &JsonValue, expected: &JsonValue) {
    assert_eq!(
        actual["toolRuns"].to_string(),
        expected["toolRuns"].to_string(),
        "toolRuns"
    );
    for key in ["entries", "contributions", "messages"] {
        assert_eq!(
            actual["context"][key].to_string(),
            expected["context"][key].to_string(),
            "context.{key}"
        );
    }
    for key in [
        "conversations",
        "entries",
        "tasks",
        "submissions",
        "documents",
    ] {
        assert_eq!(
            actual["storage"][key].to_string(),
            expected["storage"][key].to_string(),
            "storage.{key}"
        );
    }
    assert_eq!(actual.to_string(), expected.to_string());
}

fn fixture_state(name: &str) -> JsonValue {
    JsonValue::parse(&std::fs::read_to_string(fixtures().join(name)).unwrap()).unwrap()
}

/// Resume a copy of the crash fixture `crashed` in Rust; the state and the
/// JSONL files must equal what TS produced from the same storage.
async fn assert_resumes_like_ts(crashed: &str) {
    let temp = tempfile::tempdir().unwrap();
    let directory = temp.path().join("jsonl");
    copy_dir(&fixtures().join(crashed), &directory);
    let state = resume(&directory).await;
    assert_same_state(&state, &fixture_state(&format!("{crashed}-resumed.json")));
    assert_same_files(
        &files(&directory),
        &files(&fixtures().join(format!("{crashed}-resumed"))),
    );
}

/// TS → Rust: resume the storage a crashed TS process left.
#[tokio::test]
async fn resumes_ts_crash_like_ts() {
    assert_resumes_like_ts("ts-crash").await;
}

/// Rust → TS: resume the storage a crashed Rust process left; TS resumed
/// the same storage into `rust-crash-resumed*`.
#[tokio::test]
async fn resumes_rust_crash_like_ts() {
    assert_resumes_like_ts("rust-crash").await;
}

/// A crashed Rust process leaves the `rust-crash` fixture again, which is
/// the storage the crashed TS process left.
#[tokio::test]
async fn crash_leaves_the_fixture_storage() {
    if let Some(directory) = std::env::var_os(CRASH_DIR_ENV) {
        crash(Path::new(&directory)).await;
    }
    let temp = tempfile::tempdir().unwrap();
    let directory = temp.path().join("jsonl");
    crash_in_child("crash_leaves_the_fixture_storage", &directory);
    let crashed = without_session_ids(files(&directory));
    assert_same_files(
        &crashed,
        &without_session_ids(files(&fixtures().join("rust-crash"))),
    );
    assert_same_files(
        &crashed,
        &without_session_ids(files(&fixtures().join("ts-crash"))),
    );
}

/// Rewrite `fixtures/harness_cross/rust-crash` from a crashed child process;
/// rerun the TS resume over a copy of it afterwards.
#[tokio::test]
#[ignore = "regenerates a fixture"]
async fn regenerate_rust_crash_fixture() {
    if let Some(directory) = std::env::var_os(CRASH_DIR_ENV) {
        crash(Path::new(&directory)).await;
    }
    let directory = fixtures().join("rust-crash");
    if directory.exists() {
        std::fs::remove_dir_all(&directory).unwrap();
    }
    crash_in_child("regenerate_rust_crash_fixture", &directory);
}
